apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - name: flight-app
          image: flight-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/flight"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: flight-service
spec:
    ports:
        - port: 8089
          targetPort: 8089
    selector:
        app: flight
    type: LoadBalancer